---
title: "Files for MorphoJ practice"
author: "Virginia Chu"
date: "October 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#work comp
setwd("C:/Users/vmc04/Documents/GitHub/wingproj/MorphoJ shape field and lab")

#home laptop
#setwd ("C:/Users/virgc/GitHub/wingproj/MorphoJ shape field and lab")
#read in .csv
fieldw<-read.csv("2017_10_12 Field 18 details and scaled coords.csv", header=TRUE)

fieldw$Locality=factor(fieldw$Locality, c("ARS","APR","RPV","RMO","TLC","TPN","SJU"))

#make master file
field_18allcoords<-subset(fieldw, select=(c(1, 9:44)))
write.table(field_18allcoords, "Field 18 all coords.txt", quote=FALSE,sep="\t", row.names = FALSE)

#make master cov
field_18llcov<-subset(fieldw, select=c(1,7:8))
write.table(field_18llcov, "Field 18 all cov.txt", quote=FALSE,sep="\t", row.names = FALSE)
#make master classifiers
field_18allclas<-subset(fieldw, select=c(1:2,4:6))
write.table(field_18allclas, "Field 18 all class.txt", quote=FALSE,sep="\t", row.names = FALSE)

#aggregate
prelim<-aggregate(fieldw[,7:8], list(fieldw$Locality), mean)
write.table(prelim,"clipboard", sep="\t")

prelimsd<-aggregate(fieldw[,7:8], list(fieldw$Locality), sd)
write.table(prelimsd,"clipboard", sep="\t")
#subdivide based on locality
field_ARS<-subset(fieldw, Locality=="ARS", select=c(1:44))
field_APR<-subset(fieldw, Locality=="APR", select=c(1:44))
field_RPV<-subset(fieldw, Locality=="RPV", select=c(1:44))
field_RMO<-subset(fieldw, Locality=="RMO", select=c(1:44))
field_TLC<-subset(fieldw, Locality=="TLC", select=c(1:44))
field_TPN<-subset(fieldw, Locality=="TPN", select=c(1:44))
field_SJU<-subset(fieldw, Locality=="SJU", select=c(1:44))

#subsetting into coordinates
field_ARScoord<-subset(field_ARS, Locality=="ARS", select=c(1,9:44))
field_APRcoord<-subset(field_APR, Locality=="APR", select=c(1,9:44))
field_RPVcoord<-subset(field_RPV, Locality=="RPV", select=c(1,9:44))
field_RMOcoord<-subset(field_RMO, Locality=="RMO", select=c(1,9:44))
field_TLCcoord<-subset(field_TLC, Locality=="TLC", select=c(1,9:44))
field_TPNcoord<-subset(field_TPN, Locality=="TPN", select=c(1,9:44))
field_SJUcoord<-subset(field_SJU, Locality=="SJU", select=c(1,9:44))

#covariates, 
field_ARScov<-subset(field_ARS, Locality=="ARS", select=c(1,7:8))
field_APRcov<-subset(field_APR, Locality=="APR", select=c(1,7:8))
field_RPVcov<-subset(field_RPV, Locality=="RPV", select=c(1,7:8))
field_RMOcov<-subset(field_RMO, Locality=="RMO", select=c(1,7:8))
field_TLCcov<-subset(field_TLC, Locality=="TLC", select=c(1,7:8))
field_TPNcov<-subset(field_TPN, Locality=="TPN", select=c(1,7:8))
field_SJUcov<-subset(field_SJU, Locality=="SJU", select=c(1,7:8))

#and classifiers
field_ARSclas<-subset(field_ARS, Locality=="ARS", select=c(1:2,4:6))
field_APRclas<-subset(field_APR, Locality=="APR", select=c(1:2,4:6))
field_RPVclas<-subset(field_RPV, Locality=="RPV", select=c(1:2,4:6))
field_RMOclas<-subset(field_RMO, Locality=="RMO", select=c(1:2,4:6))
field_TLCclas<-subset(field_TLC, Locality=="TLC", select=c(1:2,4:6))
field_TPNclas<-subset(field_TPN, Locality=="TPN", select=c(1:2,4:6))
field_SJUclas<-subset(field_SJU, Locality=="SJU", select=c(1:2,4:6))
#make into tab delimited .txt

write.table(field_ARScoord, "Field 18 ARS coords.txt", quote=FALSE,sep="\t", row.names = FALSE)
write.table(field_APRcoord, "Field 18 APR coords.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_RPVcoord, "Field 18 RPV coords.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_RMOcoord, "Field 18 RMO coords.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_TLCcoord, "Field 18 TLC coords.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_TPNcoord, "Field 18 TPN coords.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_SJUcoord, "Field 18 SJU coords.txt", sep="\t",quote=FALSE, row.names = FALSE)

write.table(field_ARScov, "Field 18 ARS cov.txt", quote=FALSE,sep="\t", row.names = FALSE)
write.table(field_APRcov, "Field 18 APR cov.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_RPVcov, "Field 18 RPV cov.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_RMOcov, "Field 18 RMO cov.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_TLCcov, "Field 18 TLC cov.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_TPNcov, "Field 18 TPN cov.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_SJUcov, "Field 18 SJU cov.txt", sep="\t",quote=FALSE, row.names = FALSE)

write.table(field_ARSclas, "Field 18 ARS class.txt", quote=FALSE,sep="\t", row.names = FALSE)
write.table(field_APRclas, "Field 18 APR class.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_RPVclas, "Field 18 RPV class.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_RMOclas, "Field 18 RMO class.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_TLCclas, "Field 18 TLC class.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_TPNclas, "Field 18 TPN class.txt", sep="\t",quote=FALSE, row.names = FALSE)
write.table(field_SJUclas, "Field 18 SJU class.txt", sep="\t",quote=FALSE, row.names = FALSE)
```

## R Markdown

Factorial Anova resource- http://rcompanion.org/handbook/G_09.html
http://homepages.inf.ed.ac.uk/bwebb/statistics/Factorial_ANOVA_in_R.pdf

MANOVA
http://www.sthda.com/english/wiki/manova-test-in-r-multivariate-analysis-of-variance
```{r cars}
#MANOVA bits borrowed from lab wing 
library(mvnormtest)
fieldtest<-t(fieldw[7:8])
mshapiro.test(fieldtest)
qqnorm(fieldtest)

#normality satisfied

fieldwlen<-labwingdat$Wing.length..mm.
fieldcs<-labwingdat$Centroid.Size

#MANOVA
#cbind- to see if columns differ across
#do wilks like Giovan
fieldres.man<-manova(cbind(Length.mm, CS)~Locality, data=fieldw)
summary(fieldres.man,test="Wilks")
summary.aov(fieldres.man)

fieldres.man1<-manova(cbind(Length.mm, CS)~Biome, data=fieldw)
summary(fieldres.man1,test="Wilks")
summary.aov(fieldres.man1)


#factorial anova
#http://rcompanion.org/handbook/G_09.html
library(lsmeans)
library(multcompView)
library(FSA)
library(ggplot2)
library(phia)
library(car)
library(RColorBrewer)

### Order levels of the factor; otherwise R will alphabetize them

#Data$Country = factor(Data$Country,levels=unique(Data$Country))

interaction.plot(x.factor     = fieldw$Biome,
                 trace.factor = fieldw$Latitude.S, 
                 response     = fieldw$CS, 
                 fun = mean,
                 type="b",
                 col=c("red","red","salmon","salmon","sandybrown","sandybrown","goldenrod"),  ### Colors for levels of trace var.
                 pch=c(19,19, 17,17, 15, 15, 13),             ### Symbols for levels of trace var.
                 fixed=TRUE,                    ### Order by factor order in data
                 leg.bty = "o")



interaction.plot(x.factor     = fieldw$Biome,
                 trace.factor = fieldw$Locality, 
                 response     = fieldw$CS, 
                 fun = mean,
                 type="b",
                 col=c("red","red","salmon","salmon","sandybrown","sandybrown","goldenrod"),  ### Colors for levels of trace var.
                 pch=c(19,19, 17,17, 15, 15, 13),             ### Symbols for levels of trace var.
                 fixed=TRUE,                    ### Order by factor order in data
                 leg.bty = "o")
#ANOVA
model = lm(CS ~ Biome + Latitude + Biome:Latitude, data = fieldw)
Anova(model, type="II")

#if all the main effects are significant (post hoc)
library(lsmeans)

leastsquare=lsmeans(model,  pairwise ~ Biome,   adjust="tukey")       ### Tukey-adjusted comparisons

leastsquare$contrasts

cld(leastsquare,    alpha=0.05,     Letters=letters,      ### Use lower-case letters for .group
    adjust="tukey")       ### Tukey-adjusted comparisons 


##better graph?
### Create a data frame called Sum with means and standard deviations 

library(FSA) 

Sum = Summarize(CS ~ Biome + Latitude, data=fieldw, digits=3)

### Add standard error of the mean to the Sum data frame 

Sum$se = Sum$sd / sqrt(Sum$n)

Sum$se = signif(Sum$se, digits=3)

Sum

pd = position_dodge(.2)

#ggplot(Sum, aes(x = Biome,
                y = mean,
                color = Latitude)) +
    geom_errorbar(aes(ymin = mean - se,
                      ymax = mean + se),
                   width=.2, size=0.7, position=pd) +
    geom_point(shape=15, size=4, position=pd) +
    theme_bw() +
    theme(axis.title = element_text(face = "bold") + 
    ylab("Mean CS change"))

#scale_colour_brewer(palette="RdYlGn") +
#scale_colour_manual(values= c("black","red","green")) +

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
